#! /usr/bin/env python3

import sys
import hashlib

sys.path.insert(0, "/home/pace/psite")  # noqa: E402
import psite

if len(sys.argv) != 3:
   print ("usage: set-name-and-key hen_name password")
   sys.exit(1)

hen_name = sys.argv[1]
pw = sys.argv[2]

hen_key = hashlib.pbkdf2_hmac("sha256", pw.encode("utf8"), b'22906', 100000)
hen_key_hex = hen_key.hex()


psite.setvar("hen_name", hen_name)
psite.setvar("hen_key", hen_key_hex)
psite.commit()


