#! /usr/bin/env python3

import sys
import socket
import json
import hashlib
import re
import pprint

proto = {}
proto['pkts'] = {}
with open("chick-hen.proto", "r") as file:
   pktname = None
   for line in file:
      line = re.sub(re.compile("#.*" ) ,"" , line).strip()
      words = re.split ("\s+", line)
      if len(words) == 0:
         continue
      elif words[0] == "":
         continue
      elif words[0] == "pkt":
         pktname = words[1]
         proto['pkts'][pktname] = {}
         proto['pkts'][pktname]['fields'] = []
      else:
         bits = int(words[0])
         field = words[1]
         proto['pkts'][pktname]['fields'].append(dict (field=field, bits=bits))

basename = "proto-gen"

pp = pprint.PrettyPrinter(indent=4)
with open(basename+".py", "w") as file:
   file.write (pp.pformat (proto))
   file.write ("\n")

with open(basename+".h", "w") as file:
   file.write ('#include "proto-common.h"\n')
   for pktname, pdata in proto['pkts'].items():
      struct_name = "proto_"+pktname
      file.write ("struct "+struct_name+" {\n")
      for fdata in pdata['fields']:
         field = fdata['field']
         bits = fdata['bits']
         if bits <= 8:
            type = "uint8_t"
         elif bits <= 16:
            type = "uint16_t"
         else:
            type = "uint32_t"
      
         file.write ("\t"+type+" "+field+";\n")
      file.write ("};\n")
      file.write ("extern struct proto_desc "+struct_name+"_desc;\n")
      file.write ("\n")

with open(basename+".c", "w") as file:
   file.write('#include <stdio.h>\n')
   file.write('#include <stdint.h>\n')
   file.write('#include <stddef.h>\n')
   file.write('#include "proto-gen.h"\n')
   for pktname, pdata in proto['pkts'].items():
      struct_name = "proto_"+pktname
      desc_name = struct_name+"_desc"
      fields_name = struct_name+"_fields"
      fields = pdata['fields']

      file.write("struct field_desc "+fields_name+"[] = {\n")
      for fdata in fields:
         field = fdata['field']
         bits = fdata['bits']
         file.write("\t{\n")
         file.write('\t\t"'+field+'",\n')
         file.write('\t\t'+str(bits)+',\n')
         file.write('\t\toffsetof(struct '+struct_name+', '+field+'),\n')
         file.write("\t},\n")
      file.write("};\n")

      file.write("struct proto_desc "+desc_name+" = {\n")
      file.write("\t")
      file.write('"'+pktname+'", ')
      file.write(str(len(fields)) + ", ")
      file.write(fields_name + ", ")
      file.write('sizeof (struct '+struct_name+'),')
      file.write("\n")
      file.write ("};\n\n")
      


