#! /usr/bin/env python3

import sys
import re
import sqlite3

import psite

with open("schema") as f:
   table = None
   for line in f:
      line = re.sub(re.compile("#.*"), "", line).strip()
      words = re.split("\s+", line)
      if len(words) == 0:
         continue
      if words[0] == "table":
         table = words[1]
      elif words[0] == "col":
         column = words[1]
         typename = words[2]
         psite.make_column (table, column, typename)
   psite.commit()
   
