#! /usr/bin/env python3

import sys
import re
import sqlite3

import psite

filename = "schema"
with open(filename) as f:
   table = None
   linenum = 0
   for line in f:
      linenum = linenum + 1
      line = re.sub(re.compile("#.*"), "", line).strip()
      words = re.split("\s+", line)
      if len(words) == 0:
         continue
      if words[0] == "table":
         if len(words) != 2:
            raise ValueError("{}:{}: wrong number of args"
                             .format(filename,linenum))
         table = words[1]
      elif words[0] == "col":
         if len(words) != 3:
            raise ValueError("{}:{}: wrong number of args"
                             .format(filename,linenum))
         column = words[1]
         typename = words[2]
         psite.make_column (table, column, typename)
   psite.commit()
   
