#define CHICK_HEN_VERS 1

#define PKT_TO_NODENUM 0
#define PKT_FROM_NODENUM 1
#define PKT_OP 2
#define PKT_PAYLOAD 3

#define BROADCAST_NODENUM 99

#define OP_PROBE 0x40
#define OP_PROBE_RESPONSE 0x41

