#! /usr/bin/env python3

import sys
import json
import re
import os
import socket
import random
import getpass

sys.path.insert(0, "..")
import psite

def setup_db():
   cfg['db'] = get_option("db", "")

def get_free_port(port_base):
   return random.randrange(port_base, port_base + 1000)

def make_url(scheme, host, port):
   url = "{}://{}".format(scheme, host)
   if port != 80 and port != 443:
      url += ":{}".format(port)
   url += "/"
   return url

def find_certs():
   cfg.pop("crt_file", None)
   cfg.pop("key_file", None)
   cfg.pop("chain_file", None)

   if (re.match(".*.pacew.org$", cfg['external_name']) 
       and os.path.exists("/etc/apache2/wildcard.pacew.org.crt")):
      cfg['crt_file'] = "/etc/apache2/wildcard.pacew.org.crt"
      cfg['key_file'] = "/etc/apache2/wildcard.pacew.org.key"
      cfg['chain_file'] = "/etc/apache2/wildcard.pacew.org.chain.pem"
      return

   return

def make_virtual_host(ssl_flag, port):
   conf = ""

   if port != 80 and port != 443:
      conf += "Listen {}\n".format(port)

   conf += "<VirtualHost *:{}>\n".format(port)
   conf += "  ServerName {}\n".format(cfg['external_name'])
   conf += "  ServerAlias www.{}\n".format(cfg['external_name'])
   if ssl_flag:
      conf += "  SSLEngine on\n";
      conf += "  SSLCertificateFile {}\n".format(cfg['crt_file'])
      conf += "  SSLCertificateKeyFile {}\n".format(cfg['key_file'])
      if 'chain_file' in cfg:
         conf += "  SSLCertificateChainFile {}\n".format(cfg['chain_file'])
   conf += "  php_flag display_errors on\n"
   conf += "  DocumentRoot {}\n".format(cfg['www_dir'])
   conf += "  SetEnv APP_ROOT {}\n".format(cfg['srcdir'])
   conf += "  <Directory {}>\n".format(cfg['www_dir'])
   conf += "    <IfModule valhtml_module>\n"
   conf += "      AddOutputFilterByType VALHTML text/html\n"
   conf += "      SetEnv no-gzip 1\n"
   conf += "    </IfModule>\n"
   conf += "    <FilesMatch '\.(html|css)'>\n"
   conf += "      Header set Cache-Control 'no-cache,no-store,must-revalidate'\n"
   conf += "      Header set Expires 0\n"
   conf += "    </FilesMatch>\n"
   conf += "  </Directory>\n"
   conf += "  DirectoryIndex index.php\n"
   conf += "  RewriteEngine on\n"
   conf += "  RewriteCond %{REQUEST_URI} /.well-known/.*\n"
   conf += "  RewriteRule ^(.*) /var/www/html/$1 [L]\n"
   conf += "\n"

   if cfg['ssl_port'] != 0 and not ssl_flag:
      conf += "  RewriteRule ^/(.*) {}$1 [R]\n".format(cfg['main_url'])
      conf += "\n"
   else:
      conf += "  RewriteCond %{{HTTP_HOST}} www.{}\n".format(
         cfg['external_name'])
      conf += "  RewriteRule ^/(.*) {}$1 [R]\n".format(cfg['main_url'])
      conf += "\n"
   
      conf += "  RewriteCond {}%{{REQUEST_FILENAME}} !-f\n".format(
         cfg['www_dir'])
      conf += "  RewriteRule .* {}/index.php\n".format(cfg['srcdir'])

   conf += "</VirtualHost>\n"

   return conf

def setup_apache():
   conf = ""

   conf += "<Directory {}>\n".format(cfg['srcdir'])
   conf += "  Options Indexes FollowSymLinks Includes ExecCGI\n"
   conf += "  Require all granted\n"
   conf += "  Allow from all\n"
   conf += "</Directory>\n"

   cfg['www_dir'] = "/var/www/{}".format(siteid)
   if not os.path.exists(cfg['www_dir']):
      print("sudo ln -sf {} {}".format(cfg['static_dir'], cfg['www_dir']))
   if not os.path.exists(cfg['auxdir']):
      print("sudo sh -c 'mkdir -pm2775 {0}; chown www-data.www-data {0}'"
            .format(cfg['auxdir']))
   if cfg['plain_port']:
      conf += make_virtual_host(False, cfg['plain_port'])

   if cfg['ssl_port']:
      conf += make_virtual_host(True, cfg['ssl_port'])

   with open("TMP.conf", "w") as outf:
      outf.write(conf)

   av_name = "/etc/apache2/sites-available/{}.conf".format(siteid)
   en_name = "/etc/apache2/sites-enabled/{}.conf".format(siteid)

   old = psite.slurp_file(av_name)
   if old != conf:
      print("sudo sh -c 'cp TMP.conf {}; apache2ctl graceful'".format(
         av_name))

   if not os.path.exists(en_name):
      print("sudo a2ensite {}".format(siteid))


cfg = psite.read_json("cfg.json", {})

if not 'site_name' in cfg:
   if len(sys.argv) < 2:
      print("must specify site_name for install call to install-site")
      print("usage: install-site [site_name [conf_key]]")
      sys.exit(1)
   else:
      cfg['site_name'] = sys.argv[1]
      if len(sys.argv) < 3:
         cfg['conf_key'] = getpass.getuser()
      else:
         cfg['conf_key'] = sys.argv[2]

siteid = "{}-{}".format(cfg['site_name'], cfg['conf_key'])
cfg['siteid'] = siteid

server_name = socket.gethostname()

options = psite.read_json("options.json")
options_server = options.get(server_name, {})
options_site = options_server.get(siteid, {})

def get_option(name, default=None):
   if name in options_site:
      return options_site[name]
   elif name in options_server:
      return options_server[name]
   elif name in options:
      return options[name]
   else:
      return default

cfg['srcdir'] = os.getcwd()
cfg['static_dir'] = "{}/static".format(cfg['srcdir'])
cfg['auxdir'] = "/var/{}".format(cfg['siteid'])


nat_info = re.split("\s+", psite.slurp_file ("/etc/apache2/NAT_INFO"))
if len(nat_info) >= 2:
   nat_name = nat_info[0]
   port_base = int(nat_info[1])
else:
   nat_name = "localhost"
   port_base = 8000

val = get_option("external_name")
if val == None:
   cfg['external_name'] = nat_name
   if 'plain_port' not in cfg:
      cfg['plain_port'] = get_free_port(port_base)
else:
   cfg['external_name'] = val
   cfg['plain_port'] = 80
   cfg['ssl_port'] = 443


cfg['plain_url'] = make_url("http", cfg['external_name'], cfg['plain_port'])
cfg['main_url'] = cfg['plain_url']

find_certs()
if 'crt_file' in cfg:
   if cfg.get("ssl_port", 0) == 0:
      cfg['ssl_port'] = get_free_port(port_base)
   cfg['ssl_url'] = make_url("https", cfg['external_name'], cfg['ssl_port'])
   cfg['main_url'] = cfg['ssl_url']
else:
   cfg['ssl_port'] = 0
   cfg['ssl_url'] = ""

setup_db()
setup_apache()

print(cfg['plain_url'])
if cfg.get('ssl_url', None) != None:
   print(cfg['ssl_url'])

psite.write_json("cfg.json", cfg)



